// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAakJ1LBTBZq727cJCMmOBDBfCzmJYqgx4',
    appId: '1:333777144664:web:4c56d50f44c4599333f32d',
    messagingSenderId: '333777144664',
    projectId: 'women-safety-app-2-636dc',
    authDomain: 'women-safety-app-2-636dc.firebaseapp.com',
    storageBucket: 'women-safety-app-2-636dc.appspot.com',
    measurementId: 'G-NLDB3R47CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54okXtmvn5hn79kaSh6lNJxR1jvXn_ps',
    appId: '1:333777144664:android:b2e75ca1ad68fb6833f32d',
    messagingSenderId: '333777144664',
    projectId: 'women-safety-app-2-636dc',
    storageBucket: 'women-safety-app-2-636dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNP0LnBJ6yoxI4wviKMaOtlFX8dgT9z88',
    appId: '1:333777144664:ios:fb8ff0da0531add833f32d',
    messagingSenderId: '333777144664',
    projectId: 'women-safety-app-2-636dc',
    storageBucket: 'women-safety-app-2-636dc.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNP0LnBJ6yoxI4wviKMaOtlFX8dgT9z88',
    appId: '1:333777144664:ios:fb8ff0da0531add833f32d',
    messagingSenderId: '333777144664',
    projectId: 'women-safety-app-2-636dc',
    storageBucket: 'women-safety-app-2-636dc.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAakJ1LBTBZq727cJCMmOBDBfCzmJYqgx4',
    appId: '1:333777144664:web:b8f82db49370319f33f32d',
    messagingSenderId: '333777144664',
    projectId: 'women-safety-app-2-636dc',
    authDomain: 'women-safety-app-2-636dc.firebaseapp.com',
    storageBucket: 'women-safety-app-2-636dc.appspot.com',
    measurementId: 'G-5068RQ6Z53',
  );
}
